#!/bin/sh
rm -rf coverage
mkdir -p coverage
# bazel coverage --combined_report=lcov //...
# mv $(BAZEL_OUTPUT_PATH)/_coverage/_coverage_report.dat coverage/lcov.info
# go test -coverprofile=coverage/coverage.out ./...
go test -v -covermode=count -coverprofile=coverage/coverage.out ./...
# GOROOT=$(go env GOROOT) gcov2lcov -infile=coverage/coverage.txt -outfile=coverage/lcov.info