#!/bin/zsh

OLD_KEY=/private/var/root/recovery_key.plist
NEW_KEY=/private/var/root/crypt_output.plist
if [[ -f "$OLD_KEY" ]]; then
    /bin/mv $OLD_KEY $NEW_KEY
fi


# remove old crypt
OLD_CRYPT=/usr/local/crypt
if [[ -d "$OLD_CRYPT" ]]; then
    /bin/rm -r $OLD_CRYPT
fi

# remove old foundationplist, thanks for the memories.
if [[ -f "/Library/Crypt/FoundationPlist.py" ]]; then
    /bin/rm /Library/Crypt/FoundationPlist.py
fi

if [[ -f "/Library/Crypt/FoundationPlist.pyc" ]]; then
    /bin/rm /Library/Crypt/FoundationPlist.pyc
fi

# Remove python
if [[ -e "/Library/Crypt/python" ]]; then
    /bin/rm /Library/Crypt/python
fi

if [[ -d "/Library/Crypt/Python.framework" ]]; then
    /bin/rm -r /Library/Crypt/Python.framework
fi